# Generated by Django 2.0.7 on 2018-08-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20180822_2024'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClickAnalysis',
            new_name='ClickAnalytic',
        ),
    ]
