# Generated by Django 2.0.7 on 2018-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180819_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.URLField(blank=True, max_length=20, unique=True),
        ),
    ]
