# Generated by Django 2.0.7 on 2018-08-20 17:25

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20180819_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.URLField(max_length=220, validators=[shortener.validators.validate_com_url]),
        ),
    ]
